### ISSUE TITLE
When PiCAST 3 is comming?

### ISSUE THREAD

**Issue by FelixINX** [lanceseidman/PiCAST#25]
Hi,

I would like to know when PiCast 3 will be out.

Thanks

**Comment by lanceseidman** [comment]
Hi Felix,

  Sadly still trying to finish it. I unfortunately have been super busy 
in my personal Business life BUT do know, this is something that has 
already mostly been built.

Creating the ability to permit easy deployment so folks can install as a 
Binary Package as well.

**Comment by savraj** [comment]
If it could run on the $5 pi, this would be amazing / revolutionary!!!

**Comment by lanceseidman** [comment]
Hello,

 Currently being properly revised again to work on the Pi Zero. Bare with me. :)

**Comment by danboarder** [comment]
Awesome, I'm also looking forward to this try with my Pi 2.  Will it have a "screen cast" mode as well to share a desktop or powerpoint, for example?  Thanks for what you do!

**Comment by lanceseidman** [comment]
Well, trying to use WebRTC for remote desktop view but otherwise a 3rd 
party feature may be forced (e.g. VNC).

**Comment by danboarder** [comment]
Thanks @lanceseidman for the update! I can help test if needed (I have Mac, Windows, Linux, and Android systems here handy).

**Comment by lanceseidman** [comment]
Days and almost a year of waiting, the easy, super tiny coded PiCAST is on its way & available as a node project.
