### ISSUE TITLE
PiCast doesnt start

### ISSUE THREAD

**Issue by Kurainu** [lanceseidman/PiCAST#51]
When i install forever it has this error
![screenshot_1](https://cloud.githubusercontent.com/assets/15718492/22627153/9debd42e-ebbd-11e6-8d37-c7b1d4d16c62.png)

and when i try to run this this error comes
![screenshot_16](https://cloud.githubusercontent.com/assets/15718492/22627105/5d55b53e-ebbc-11e6-88f0-d76b5e8be220.png)

**Comment by lanceseidman** [comment]
So what is happening is express didn't get installed. Please use NPM to do an install of express.

**Comment by theonlyShiro** [comment]
Sorry again for the stupid question but when i go the the url and give it the youtube video id it says only Streaming youtube video... i also tryed on my tv and second monitor but nothing happens.

**Comment by jbabu** [comment]
Picast 3 not working any more in my raspberry pi 3 device. Please provide tutorial @lanceseidman

**Comment by DevonLian** [comment]
@theonlyShiro @jbabu  I can maybe help, what's the issue ?

**Comment by theonlyShiro** [comment]
@DevonLian So the Problem is When try to stream a youtube video it says streaming youtube video but nothing happens. and look at my first post. but i have installed the express module

**Comment by DevonLian** [comment]
PiCAST uses livestreamer to stream videos. However, livestreamer is not developped anymore it seems. There's a fork of it : streamlink.

Youtube often changes it settings, thus making unupdated tools to fail to fetch its videos. 

1). Try using the command line to launch a youtube video using livestreamer 
`livestreamer URL`

And give us the output. It always failed for me, telling me that "no plugin was able to handle that url"

**Comment by theonlyShiro** [comment]
@DevonLian this comes up 
![f24ce28dd42d4b37ab64174cdbb6db7e](https://cloud.githubusercontent.com/assets/15718492/23106786/fa7851e6-f6f2-11e6-9964-3601eaf2821b.png)

**Comment by DevonLian** [comment]
@theonlyShiro I've experimented the same issue on my Raspberry Pi. Few infos : 
- It seems to be an issue on ARM architectures [https://github.com/chrippa/livestreamer/issues/979](Livestreamer - Issues) and I managed to stream your video on my linux laptop.
- Livestreamer isn't maintained [https://github.com/chrippa/livestreamer/issues/979](See this Thread). Streamlink is the maintained version of it
- However Streamlink nor Livestreamer will support most of Youtube videos/music, producing this error : 
[https://github.com/streamlink/streamlink/issues/564](error: This plugin does not support protected videos, try youtube-dl instead)

So i'd recommend switching from livestreamer/streamlink to youtube-dl. You can do this by modifying the code in picast.js, and replace it to combine youtube-dl and a media player such as omxplayer.

Another streaming solution here : 
https://github.com/DevonLian/PYCASTER

It's my version of @lanceseidman PiCAST, i fixed livestreamer's issues and improved the GUI.

**Comment by lanceseidman** [comment]
You need to do forever start <filename.js>
