### ISSUE TITLE
Black and white lines on mplayer

### ISSUE THREAD

**Issue by Benspring100** [lanceseidman/PiCAST#58]
Its almost like my Pi 2 can't keep up? The Mplayer shows the program but has loads and loads of black and white lines on it.

![20170905_125203](https://user-images.githubusercontent.com/7441281/30059959-41d928b2-9239-11e7-972d-42b45f2fb7ae.jpg)

**Comment by lanceseidman** [comment]
Yeah, sadly this would be a mPlayer issue.
