### ISSUE TITLE
Optional `sudo apt-get upgrade`

### ISSUE THREAD

**Issue by azuenko** [lanceseidman/PiCAST#61]
Would it be possible to not to perform the system upgrade unconditionally? I'm not sure that all packages should receive their minor updates to make PiCAST work. But it takes a heck amount of time and risky to do without a backup.  

What can be done instead:

* [Y/n] to `apt-get upgrade`, and wait for response
* [Y/n] to `apt-get upgrade` with timeout defaulting to Yes
* Check if the system needs upgrade. If yes, stop and provide the option to restart with force flag
* Do not do automating upgrade at all, instead add "do apt-get upgrade" in Troubleshooting section in README.   

Thanks. 

PS. Still waiting upgrade to terminate.

**Comment by fschaupp** [comment]
We can simply create a setup-routine without updateing the system

**Comment by lanceseidman** [comment]
You can do anything you want. The project was meant to run as a standalone, not an addition to something. So, make whatever change suites your needs.
