### ISSUE TITLE
Oculus Quest 2 Casting... is there something here?

### ISSUE THREAD

**Issue by Paulie420** [lanceseidman/PiCAST#67]
The Oculus Quest 2 VR headset can cast its video to a Chromecast, so that friends and family can watch what you're experiencing in VR.

I want to use my Raspberry Pi to cast that video to my television. *IF* it were just an http:// I could make the magic happen from there, so I started to look at this PiCast project.

I need to do some research, as one can cast the Quest 2 to an iPhone, Android Device or Chromecast - but I don't know, technically, how its doing so... anyone have any tips, suggestions or roadblocks to this? I'll post any updates if I get PiCast working for this use case, but thought I'd drop a line first.

Thanks for any input or discussion.

**Comment by lanceseidman** [comment]
Hello,

 What are you trying to accomplish? This features is built into the headset.
